libazureinit: rustdocs for error, http, goalstate, IMDS, unittest
Azure/azure-init pull request #129
Opened 2024-09-17 12:00 UTC by dongsupark

Add rustdocs for error, http, goalstate, IMDS, unittest with examples if possible.

See also https://github.com/Azure/azure-init/issues/127.

## Testing done

Rustdocs can be checked via web like:
```
$ cargo doc --open
```

Rustdocs tests passed.

```
$ cargo test --doc
```

2024-10-07 21:00 UTC, jeremycline requested changes
Awesome, thanks for adding all this documentation. I have a few little nit-picks, but nothing major.

2024-10-08 13:55 UTC, dongsupark commented on libazureinit/src/error.rs
> +/// Set of error codes that can be used libazureinit as well as its relevant code.
Done

2024-10-08 13:55 UTC, dongsupark commented on libazureinit/src/goalstate.rs
> +/// Container of goalstate of the virtual machine. Metadata is written in XML format.
Thanks for the tip, done

2024-10-08 13:55 UTC, dongsupark commented on libazureinit/src/goalstate.rs
> +/// # use std::time::Duration;
Done

2024-10-08 13:57 UTC, dongsupark commented on libazureinit/src/error.rs
> +/// }
Agreed in general, but I am having hard time to write a clean compilable example code for that. Will look into it tomorrow again.

2024-10-15 09:34 UTC, dongsupark commented on libazureinit/src/error.rs
> +/// }
Updated the example code, thanks.

2024-10-16 17:08 UTC, merged