libazureinit: Add README
Azure/azure-init pull request #75
Opened 2024-03-27 16:08 UTC by dongsupark

Add initial README in `libazureinit`, to be published to its `crates.io` website as well.

Add a link to `libazureinit` on the top-level `azure-init` README.

2024-03-27 16:32 UTC, anhvoms requested changes

2024-03-27 16:32 UTC, anhvoms commented on libazureinit/README.md
> +Features would include like:
```suggestion
Features:
```

2024-03-27 16:32 UTC, anhvoms commented on libazureinit/README.md
> +* minimal configurations of virtual machines
```suggestion
* retrieve provisioning metadata from Azure Instance Metadata Service
* configure the VM according to the provisioning metadata
* report provisioning complete to Azure platform
```

2024-03-27 16:32 UTC, anhvoms commented on libazureinit/README.md
> +On the other hand, [azure-init](https://github.com/Azure/azure-init) is a reference implementation which actually calls API provided by libazureinit.
```suggestion
[azure-init](https://github.com/Azure/azure-init) is reference implementation that leverages the APIs provided by libazureinit.
```

2024-03-27 16:32 UTC, anhvoms commented on libazureinit/README.md
> +Goal is to make the library provide common API to be used by other provisioning implementations.
The goal is to provide APIs to for other components to perform VM provisioning on Azure platform.

2024-03-28 14:02 UTC, dongsupark commented
Done, thanks.

2024-03-28 14:24 UTC, anhvoms approved these changes

2024-03-28 14:24 UTC, anhvoms commented on libazureinit/README.md
> +[azure-init](https://github.com/Azure/azure-init) is reference implementation that leverages the APIs provided by libazureinit.
```suggestion
[azure-init](https://github.com/Azure/azure-init) is a reference implementation that leverages the APIs provided by libazureinit.
```

2024-03-28 15:08 UTC, merged